### ISSUE TITLE
Could NOT find NetCDF (missing: NetCDF_C_INCLUDEDIR NetCDF_F90_INCLUDEDIR NetCDF_F90_LIBRARIES) (found version "")

### ISSUE THREAD

**Issue by AdrienDams** [HPSCTerrSys/eCLM#12]
Hi,
I am Adrien Damseaux, PhD student working with Heidrun Matthes at AWI Potsdam.

I tried to build eCLM on DKRZ mistral but I have some netCDF library issues. It seems there is no module to set netCDF paths on mistral. I need to specify a path for netcdf_c and netcdf_f.

I try to build like below but it's not working. Do you think it is possible to build eCLM in my case?

`cmake -S src -B "$BUILD_DIR" \
>       -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
>       -DCMAKE_C_COMPILER=mpicc \
>       -DCMAKE_Fortran_COMPILER=mpifort \
>       -DCMAKE_PREFIX_PATH=/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.3-parallel-openmpi2-intel14/ \
>       -DCMAKE_PREFIX_PATH=/sw/rhel6-x64/netcdf/netcdf_c-4.4.0-parallel-openmpi2-intel14/ \
>       -DCMAKE_PREFIX_PATH=/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.1-openmpi2-intel14/`

You can find my log here:
[CMakeOutput.log](https://github.com/HPSCTerrSys/eCLM/files/8042071/CMakeOutput.log)

Thanks!

**Comment by kvrigor** [comment]
Hi! Multiple `CMAKE_PREFIX_PATH`s should be colon-separated:

```sh
NETCDF_C=/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.3-parallel-openmpi2-intel14
NETCDF_FORTRAN=/sw/rhel6-x64/netcdf/netcdf_c-4.4.0-parallel-openmpi2-intel14
PNETCDF=/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.1-openmpi2-intel14

cmake -S src -B "$BUILD_DIR"
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpifort \
      -DCMAKE_PREFIX_PATH="$NETCDF_C:$NETCDF_FORTRAN:$PNETCDF"
```

If you encounter further build issues, please send the output of the `cmake` command and `$BUILD_DIR/CMakeCache.txt`.

**Comment by AdrienDams** [comment]
Thank you for your reply! This did not solve my problem. Here are the files you requested

[CMake.output.txt](https://github.com/HPSCTerrSys/eCLM/files/8059885/CMake.output.txt)
[CMakeCache.txt](https://github.com/HPSCTerrSys/eCLM/files/8059886/CMakeCache.txt)
[CMakeOutput.log](https://github.com/HPSCTerrSys/eCLM/files/8059887/CMakeOutput.log)

**Comment by kvrigor** [comment]
Mistral's netCDF libraries are quite old. eCLM requires at least `netCDF-C 4.7.4` and `netCDF-Fortran 4.5.2`. However, you can still try using this workaround:

```sh
netcdf_pc=/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.3-parallel-openmpi2-intel14/lib64/pkgconfig
netcdff_pc=/sw/rhel6-x64/netcdf/netcdf_c-4.4.0-parallel-openmpi2-intel14/lib64/pkgconfig
pnetcdf_pc=/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.1-openmpi2-intel14/lib64/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$netcdf_pc:netcdff_pc:$pnetcdf_pc

cmake -S src -B "$BUILD_DIR"
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpifort
```

This may get you past the configure step, but I foresee you would encounter other netcdf issues during build. A long term solution would be to request your HPC admin to upgrade the netCDF libraries in your cluster. Anyway please try workaround first, and then figure out the next steps based on what kind of errors you get.

**Comment by AdrienDams** [comment]
Still not

[CMake.output.txt](https://github.com/HPSCTerrSys/eCLM/files/8060682/CMake.output.txt)
[CMakeCache.txt](https://github.com/HPSCTerrSys/eCLM/files/8060683/CMakeCache.txt)
[CMakeOutput.log](https://github.com/HPSCTerrSys/eCLM/files/8060684/CMakeOutput.log)

I had a similar problem when trying to upgrade ESCOMP/CTSM and contacted our Mistral administrator. They told me to wait until their new HPC server "Levante" came online and that they could not work on my library issues until then. I'm afraid I'll have to wait for Levante before using eCLM as well.

Thanks anyway

**Comment by AdrienDams** [comment]
It's now working well on Levante (the new DKRZ server which should replace Mistral).

Here is how I have done it:

```
netcdf_pc=/sw/spack-levante/netcdf-c-4.8.1-qk24yp/lib/pkgconfig
netcdff_pc=/sw/spack-levante/netcdf-fortran-4.5.3-k6xq5g/lib/pkgconfig
pnetcdf_pc=/sw/spack-levante/parallel-netcdf-1.12.2-sj3t4t/lib/pkgconfig
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$netcdf_pc:netcdff_pc:$pnetcdf_pc

cmake -S src -B "$BUILD_DIR" \
      -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      -DCMAKE_C_COMPILER=mpicc \
      -DCMAKE_Fortran_COMPILER=mpifort
```

**Comment by kvrigor** [comment]
Closing this issue. Further Levante build issues are being discussed in #13
