### ISSUE TITLE
build eCLM on Ubuntu-22.04 using github action

### ISSUE THREAD

**Issue by kongdd** [HPSCTerrSys/eCLM#26]
This is an example about how to build eCLM on Ubuntu-22.04 using github action. 
Hope that helps for other users.

<https://github.com/CUG-hydro/eCLM/actions>.

It will be great if a running case could be added.

**Comment by kvrigor** [comment]
That looks good @kongdd! Would you mind sharing your changes via a pull request? We can use the single point [Wuestebach](https://github.com/HPSCTerrSys/eCLM?tab=readme-ov-file#run-sample-test-case) as a test case for the CI, which I can help to add once the GitHub actions are in place.

**Comment by kongdd** [comment]
Thank you @kvrigor. It was at https://github.com/HPSCTerrSys/eCLM/pull/27

**Comment by kvrigor** [comment]
PR merged, thanks for your contribution @kongdd !
