### ISSUE TITLE
How to include CLM5 (release) developments in eCLM

### ISSUE THREAD

**Issue by tboas** [HPSCTerrSys/eCLM#37]
How do we go on about new interesting developments in the CLM5 release (or local) for eCLM?
For example, I would be interested to include developments on improved Nitrogen cycling (https://doi.org/10.5194/gmd-16-5783-2023) and representation of more cash crops (e.g. https://doi.org/10.5194/egusphere-2024-1431).

**Comment by DCaviedesV** [comment]
This is a topic that is in discussion already here: https://gitlab.jsc.fz-juelich.de/HPSCTerrSys/tsmp-internal-development-tracking/-/issues/75. @tboas could you migrate your question there?
